Maksim P.: homework for lesson 4 done
eugene-okulik/Seetgood pull request #3
Opened 2024-07-03 07:51 UTC by Seetgood

2024-07-03 10:04 UTC, eugene-okulik requested changes
Всё отлично, но одну проверку на внимательность не прошел )))

2024-07-03 10:04 UTC, eugene-okulik commented on homework/maksim_pyshny/lesson_4/lesson_4_exercise_1.py
> +my_dict['dict'].update({'i am a tuple': (200, 201, 202, 203, 204)})
В задании было:

> добавьте элемент с ключом ('i am a tuple',) и любым значением

У тебя выполнено как если бы там было

> добавьте элемент с ключом 'i am a tuple' и любым значением

`('i am a tuple',) ` - кортеж с одним элементом. И именно это и должно быть ключом. Сейчас ключ - строка `'i am a tuple'`

2024-07-03 10:51 UTC, Seetgood commented on homework/maksim_pyshny/lesson_4/lesson_4_exercise_1.py
> +my_dict['dict'].update({'i am a tuple': (200, 201, 202, 203, 204)})
внес правки

2024-07-04 07:57 UTC, eugene-okulik approved these changes

2024-07-04 07:57 UTC, merged